blogger_app/app.py
from flask import Flask, request, redirect, url_for, session
from blueprints.admin import admin_bp
from blueprints.home import home_bp
from blueprints.blog import blog_bp
import os

app = Flask(__name__)
app.secret_key = 'secret_key'

endpoints = ['blogger', 'new_blog']

@app.before_request
def before_request():
    if request.endpoint in endpoints:
        if not session.get("is_login") or not 'is_login' in session:
            return redirect(url_for('admin_login_page'))

app.register_blueprint(blog_bp)
app.register_blueprint(admin_bp)
app.register_blueprint(home_bp)

if __name__ == "__main__":

    directory = 'blog_db/'
    if not os.path.exists(directory) and not os.path.isdir(directory):
        os.makedirs(directory)
    app.run(debug=True)

blogger_app/blueprints/admin/__init__.py
from flask import Blueprint

admin_bp = Blueprint("admin", __name__, url_prefix='/admin')
from . import routes

blogger_app/blueprints/admin/routes.py
from . import admin_bp
from flask import session, redirect, request, render_template, url_for

@admin_bp.route('/', methods=['POST','GET'])
def admin_login_page():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']
        if email == 'admin@mail.com' and password == 'admin':
            session['is_login'] = True
            return redirect(url_for('blog.blogger'))
    if session.get("is_login"):
        return redirect(url_for('blog.blogger'))
    return render_template('admin/admin_login.html')

@admin_bp.route("/logout")
def logout():
    session.pop('is_login', None)
    return redirect(url_for('admin.admin_login_page'))

blogger_app/blueprints/blog/__init__.py
from flask import Blueprint

blog_bp = Blueprint('blog', __name__, url_prefix='/blog')

from . import routes

blogger_app/blueprints/blog/routes.py
from . import blog_bp
from flask import session, render_template, redirect, url_for, request, flash
import os
import json
from fetch_blog import fetch_blogs

@blog_bp.route("/")
def blogger():
    if session.get('is_login'):
        return render_template("blog/blogger.html", blogs=fetch_blogs())
    return redirect(url_for('admin.admin_login_page'))

@blog_bp.route("/<blog_title>")
def read_blog(blog_title):
    filename = f"blog_db/{blog_title}.json"
    with open(filename, 'r') as file:
        data = json.load(file)
    title = data['title']
    pub_date = data['publish_date']
    content = data['article_content']
    context = {
        'title': title,
        'pub_date': pub_date,
        'content': content
    }
    return render_template('blog/blog_article.html', **context)

@blog_bp.route("/new_blog", methods=['POST','GET'])
def new_blog():
    if request.method == 'POST':
        title = request.form['title']
        publish_date = request.form['publish_date']
        article_content = request.form['content']
        data = {
            'title': title,
            'publish_date': publish_date,
            'article_content': article_content
        }
        filename = "blog_db/" + title + ".json"
        with open(filename, 'w') as file:
            json.dump(data, file, indent=4)
        return redirect(url_for('blog.blogger'))
    return render_template('blog/new_blog.html')

@blog_bp.route('/edit', defaults={'blog': None}, methods=['GET', 'POST'])
@blog_bp.route("/edit/<blog>", methods=['POST', 'GET'])
def edit_blog(blog):
    if request.method == 'POST':
        title = request.form['title']
        publish_date = request.form['publish_date']
        article_content = request.form['content']
        data = {
            'title': title,
            'publish_date': publish_date,
            'article_content': article_content
        }
        filename = "blog_db/" + title + ".json"
        with open(filename, 'w') as file:
            json.dump(data, file, indent=4)
        flash("Blog updated", 'success')
        return redirect(url_for('blog.blogger'))

    filename = f"blog_db/{blog}.json"
    if not os.path.exists(filename):
        flash("Error. Blog not found", 'error')
        return redirect(url_for('blog.blogger'))
    with open(filename, 'r', encoding='utf-8') as file:
        data = json.load(file)
    context = {
    'title': data['title'],
    'pub_date': data['publish_date'],
    'content': data['article_content'],
    }
    return render_template('blog/edit_blog.html', **context)
    

@blog_bp.route("/delete/<blog>")
def delete_blog(blog):
    filename = f"blog_db/{blog}.json"
    if os.path.exists(filename):
        os.remove(filename)
        flash("Blog deleted.", 'success')
    else:
        flash("Error blog not found.", "error")
    return redirect(url_for('blog.blogger'))

blogger_app/blueprints/home/__init__.py
from flask import Blueprint
home_bp = Blueprint('home', __name__)
from . import routes

blogger_app/blueprints/home/routes.py
from . import home_bp
from flask import render_template
from fetch_blog import fetch_blogs

@home_bp.route('/')
def home_page():
    return render_template('home/index.html', blogs=fetch_blogs())

blogger_app/templates/admin_login.html
{% extends 'base.html' %}
{% block title %}
Admin Login
{% endblock title %}

{% block body %}
<h1>Admin Login.</h1>
<form action="{{ url_for('admin_login_page') }}" method="post">
    <label for="email">
        Email<br>
        <input type="email" name="email" id="email">
    </label>
    <br>
    <label for="password">
        Password<br>
        <input type="password" name="password" id="password">
    </label>
    <br>
    <input type="submit" value="Login">
</form>
{% endblock body%}

blogger_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@1.0.2/css/bulma.min.css">
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
    <div class="flash-messages">
        {% with messages= get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    <p class="{{ category }}">{{ message }}</p>
                {% endfor %}
            {% endif %}
        {% endwith %}
    </div>
    {% block body %}
    {% endblock %}
</body>
</html>

blogger_app/templates/blog/blog_article.html
{% extends 'base.html' %}
{% block title %}
Article
{% endblock title %}

{% block body %}
<div class="container">
    <h1 class="is-size-2 has-background-info">{{ title }}</h1>
    <p class="is-italic">Published on {{ pub_date }}</p>
    <br>
    <p class="is-sized-4 has-text-weight-bold">Article start here:</p>
    <p>{{ content }}</p>
</div>
{% endblock body%}

blogger_app/templates/blog/blogger.html
{% extends 'base.html' %}
{% block title %}
Blogger
{% endblock title %}

{% block body %}
<div class="container">
    <nav class="navbar" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
            <h1 class="is-size-1">Welcome, Admin</h1>
            <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false">
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
            </a>
        </div>
        <div class="navbar-end">
            <div class="navbar-item">
                <div class="buttons">
                    <a href="{{ url_for('admin.logout') }}" class="button is-primary"><strong>Logout</strong></a>
                </div>
            </div>
        </div>
    </nav>
    <p><a href="{{ url_for('blog.new_blog') }}"><button class="button is-primary">Add new blog</button></a></p>
    <br>
    {% for blog in blogs %}
    <div class="card">
        <div class="card-content">
          <div class="content">
            <p>{{ blog }}</p>
          </div>
        </div>
        <footer class="card-footer">
            <a href="{{ url_for('blog.edit_blog', blog=blog) }}" class="card-footer-item">Edit</a>
            <a href="{{ url_for('blog.delete_blog', blog=blog) }}" class="card-footer-item">Delete</a>
        </footer>
      </div>
    {% endfor %}
</div>
{% endblock body%}

blogger_app/templates/blog/edit_blog.html
{% extends 'base.html' %}
{% block title %}
Edit Blog
{% endblock title %}

{% block body %}
<div class="container">
    <h1 class="is-size-2 has-background-info mb-3">Edit blog</h1>
    <form action="{{ url_for('blog.edit_blog') }}" method="post">
        <input type="text" name="title" id="title" placeholder="Article Title" required class="input" value="{{ title }}">
        <br><br>
        <input type="date" name="publish_date" id="publish_date" placeholder="publish_date" required class="input" value="{{ pub_date }}">
        <br><br>
        <textarea name="content" id="content" cols="60" rows="10" placeholder="Enter content" class="textarea">{{ content }}</textarea>
        <br>
        <input type="submit" value="Update" class="button is-info">
    </form>
</div>
{% endblock body%}

blogger_app/templates/blog/new_blog.html
{% extends 'base.html' %}
{% block title %}
New Blog
{% endblock title %}

{% block body %}
<div class="container">
    <h1 class="is-size-2 has-background-info mb-3">New blog</h1>
    <form action="{{ url_for('blog.new_blog') }}" method="post">
        <input type="text" name="title" id="title" placeholder="Article Title" required class="input">
        <br><br>
        <input type="date" name="publish_date" id="publish_date" placeholder="publish_date" required class="input">
        <br><br>
        <textarea name="content" id="content" cols="60" rows="10" placeholder="Enter content" class="textarea"></textarea>
        <br>
        <input type="submit" value="Publish" class="button is-info">
    </form>
</div>

{% endblock body%}

blogger_app/templates/home/index.html
{% extends 'base.html' %}
{% block title %}
Home
{% endblock title %}

{% block body %}
<div class="container">
    <h1 class="is-size-2-tablet is-size-4-mobile has-text-centered">Welcome to personal blog.</h1>
    {% for blog in blogs %}
    <div class="card ml-3 mr-2 is-radiusless is-size-3">
        <div class="content px-2">
            <p><a href="{{ url_for('blog.read_blog', blog_title=blog) }}">{{ blog }}</a></p>
        </div>
    </div>
{% endfor %}
</div>

{% endblock body%}

blogger_app/templates/index.html
{% extends 'base.html' %}
{% block title %}
Home
{% endblock title %}

{% block body %}
<h1>Welcome to personal blog.</h1>
{% endblock body%}

blogger_app/templates/new_blog.html
{% extends 'base.html' %}
{% block title %}
New Blog
{% endblock title %}

{% block body %}
<h1>New blog.</h1>
<form action="{{ url_for('new_blog') }}" method="post">
    <input type="text" name="title" id="title" placeholder="Article Title" required>
    <br><br>
    <input type="date" name="publish_date" id="publish_date" placeholder="publish_date" required>
    <br><br>
    <textarea name="content" id="content" cols="100" rows="30" placeholder="Enter content"></textarea>
    <br>
    <input type="submit" value="Publish">
</form>
{% endblock body%}